import ROOT
import numpy as np

ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetPalette(ROOT.kRainBow)
ROOT.gROOT.SetBatch(True)

outfolder = "/home/nitish/public_html/shared/end/efficiency/domPE/"
fin1 = ROOT.TFile("hists_numu_pen_small_domPE.root", "read")
fin2 = ROOT.TFile("hists_numu_pen_middle_domPE.root", "read")
fin3 = ROOT.TFile("hists_numu_pen_small_equalx_domPE.root", "read")
fin4 = ROOT.TFile("hists_numu_aframe_spacing5m_domPE.root", "read")
fin5 = ROOT.TFile("hists_numu_long_domPE.root", "read")

hdom1 = fin1.Get("hnDoms")
hdom2 = fin2.Get("hnDoms")
hdom3 = fin3.Get("hnDoms")
hdom4 = fin4.Get("hnDoms")
hdom5 = fin5.Get("hnDoms")

hxy1 = fin1.Get("fid_xy")
hxy1_tot = fin1.Get("fid_tot_xy")
hxy1.Divide(hxy1_tot)
hxy1.SetTitle("Avg. Number of DOMs Fired per Event")
hxy1.GetXaxis().SetTitle("Vertex X")
hxy1.GetYaxis().SetTitle("Vertex Y")

hxy2 = fin2.Get("fid_xy")
hxy2_tot = fin2.Get("fid_tot_xy")
hxy2.Divide(hxy2_tot)
hxy2.SetTitle("Avg. Number of DOMs Fired per Event")
hxy2.GetXaxis().SetTitle("Vertex X")
hxy2.GetYaxis().SetTitle("Vertex Y")

hxy3 = fin3.Get("fid_xy")
hxy3_tot = fin3.Get("fid_tot_xy")
hxy3.Divide(hxy3_tot)
hxy3.SetTitle("Avg. Number of DOMs Fired per Event")
hxy3.GetXaxis().SetTitle("Vertex X")
hxy3.GetYaxis().SetTitle("Vertex Y")

hxy4 = fin4.Get("fid_xy")
hxy4_tot = fin4.Get("fid_tot_xy")
hxy4.Divide(hxy4_tot)
hxy4.SetTitle("Avg. Number of DOMs Fired per Event")
hxy4.GetXaxis().SetTitle("Vertex X")
hxy4.GetYaxis().SetTitle("Vertex Y")

hxy5 = fin5.Get("fid_xy")
hxy5_tot = fin5.Get("fid_tot_xy")
hxy5.Divide(hxy5_tot)
hxy5.SetTitle("Avg. Number of DOMs Fired per Event")
hxy5.GetXaxis().SetTitle("Vertex X")
hxy5.GetYaxis().SetTitle("Vertex Y")

hyz1 = fin1.Get("fid_yz")
hyz1_tot = fin1.Get("fid_tot_yz")
hyz1.Divide(hyz1_tot)
hyz1.SetTitle("Avg. Number of DOMs Fired per Event")
hyz1.GetXaxis().SetTitle("Vertex Z")
hyz1.GetYaxis().SetTitle("Vertex Y")

hyz2 = fin2.Get("fid_yz")
hyz2_tot = fin2.Get("fid_tot_yz")
hyz2.Divide(hyz2_tot)
hyz2.SetTitle("Avg. Number of DOMs Fired per Event")
hyz2.GetXaxis().SetTitle("Vertex Z")
hyz2.GetYaxis().SetTitle("Vertex Y")

hyz3 = fin3.Get("fid_yz")
hyz3_tot = fin3.Get("fid_tot_yz")
hyz3.Divide(hyz3_tot)
hyz3.SetTitle("Avg. Number of DOMs Fired per Event")
hyz3.GetXaxis().SetTitle("Vertex Z")
hyz3.GetYaxis().SetTitle("Vertex Y")

hyz4 = fin4.Get("fid_yz")
hyz4_tot = fin4.Get("fid_tot_yz")
hyz4.Divide(hyz4_tot)
hyz4.SetTitle("Avg. Number of DOMs Fired per Event")
hyz4.GetXaxis().SetTitle("Vertex Z")
hyz4.GetYaxis().SetTitle("Vertex Y")

hyz5 = fin5.Get("fid_yz")
hyz5_tot = fin5.Get("fid_tot_yz")
hyz5.Divide(hyz5_tot)
hyz5.SetTitle("Avg. Number of DOMs Fired per Event")
hyz5.GetXaxis().SetTitle("Vertex Z")
hyz5.GetYaxis().SetTitle("Vertex Y")

#  c = ROOT.TCanvas("c", "", 1000, 500)
#  cols = [ROOT.kBlack, ROOT.kRed, ROOT.kGreen+2, ROOT.kBlue, ROOT.kViolet]
#  keys = ["pen_small", "pen_middle", "pen_small_rockbed", "3d", "long"]
#  i = 0
#  leg = ROOT.TLegend(0.65, 0.5, 0.85, 0.75)
#  for h in [hdom1, hdom2, hdom3, hdom4, hdom5]:
#      h.Scale(1./h.Integral())
#      h.Draw("hist same")
#      h.SetLineColor(cols[i])
#      h.SetLineWidth(2)
#      h.GetXaxis().SetTitle("Number of DOMs with PE >= 3")
#      h.GetYaxis().SetTitle("Fraction of Events")
#      leg.AddEntry(h, keys[i], "le")
#      i += 1
#
#  leg.Draw()
#  c.SetLogy()
#  c.Print(outfolder+"ndoms_dist.pdf")

#  c.Divide(2, 1)
#  c.cd(1)
#  hdom1.GetXaxis().SetTitle("DOM Number")
#  #  hdom1.GetYaxis().SetTitle("DOM Number")
#  hdom1.Draw("colz")
#  hdom1.SetTitle("3D Array (Longitudinal Beam)")
#  hdom1.GetZaxis().SetRangeUser(0, 0.0021)
#  ROOT.gPad.SetRightMargin(0.15)
#  ROOT.gPad.SetLeftMargin(0.075)
#  c.cd(2)
#  hdom2.GetXaxis().SetTitle("DOM Number")
#  #  hdom2.GetYaxis().SetTitle("DOM Number")
#  hdom2.Draw("colz")
#  hdom2.SetTitle("Large Array (Longitudinal Beam)")
#  hdom2.GetZaxis().SetRangeUser(0, 0.0021)
#  ROOT.gPad.SetRightMargin(0.15)
#  ROOT.gPad.SetLeftMargin(0.075)
#  c.Print(outfolder+"dom_efficiency.pdf")

c = ROOT.TCanvas("c", "", 1000, 500)
c.Divide(2, 1)
c.cd(1)
hxy1.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.cd(2)
hyz1.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.Print(outfolder+"fid_pen_small.pdf")

c = ROOT.TCanvas("c", "", 1000, 500)
c.Divide(2, 1)
c.cd(1)
hxy2.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.cd(2)
hyz2.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.Print(outfolder+"fid_pen_middle.pdf")

c = ROOT.TCanvas("c", "", 1000, 500)
c.Divide(2, 1)
c.cd(1)
hxy3.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.cd(2)
hyz3.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.Print(outfolder+"fid_pen_small_equalx.pdf")

c = ROOT.TCanvas("c", "", 1000, 500)
c.Divide(2, 1)
c.cd(1)
hxy4.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.cd(2)
hyz4.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.Print(outfolder+"fid_aframe_spacing5m.pdf")

c = ROOT.TCanvas("c", "", 1000, 500)
c.Divide(2, 1)
c.cd(1)
hxy5.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.cd(2)
hyz5.Draw("colz")
ROOT.gPad.SetRightMargin(0.15)
ROOT.gPad.SetLeftMargin(0.075)
c.Print(outfolder+"fid_long.pdf")
